- name: variables
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name: print override information
    ansible.builtin.debug:
      msg: "Hello., I am learning {{ Course }} from trainer {{ Trainers }}, duration is {{ Duration }}."    