172.31.21.222

[web]
172.31.29.185

[web:vars]
DB_URL="http://db.venkymadhumanchi.shop"

[localhost]
locahost

[localhost:vars]
Course="DevOps with AWS"
Trainer="venky"
Duration="120hrs"
Timings="12:52pm IST"
#WISHES="Morning from inventory"

[db]
172.31.21.219

[app]
172.31.21.220

[all:children]
web
db
app