172.31.21.222

[web]
172.31.21.218

[web:vars]
DB_URL="http://db.venkymadhumanchi.shop"

[localhost]
locahost

[localhost:vars]
Course:"DevOps with AWS"
Trainer:"venky"
Duration:"120hrs"

[db]
172.31.21.219

[app]
172.31.21.220

[all:children]
web
db
app